### PR TITLE
indexes are corrected for unequal image axes

### PR DESCRIPTION
**Pull request by queezz**
LED spectrum, plotting using np_open and imshow()
Before correction
shape0

After correction

shape1

### CODE REVIEW

**Comment by fujiisoup** [comment]
Thank you for the PR.

I will configure CI so that it could build test on this PR.

**Comment by fujiisoup** [comment]
This patch looks working also for the other images I have.
(Don't care about travis.)

Thanks a lot!

**Comment by fujiisoup** [comment]
Forgot one thing.

Can you send another PR with an appropriate test?
It is important so that another change does not break your fix.

+ Add your LED.SIF into `testings/examples`
+ Add your 'correct' result in `testings/examples` (maybe `LED.npy`?)
+ Add a test script in `testings/test_open.py`

**Comment by queezz** [comment]
I can send my image and result. But I don't know how to make a test for git.

**Comment by fujiisoup** [comment]
@queezz 
Yes, add your file in `testings/examples/` with the correct result.

Unittest is neat.
Even if you develop some your own script, test script for it really helps.

See [test driven development](https://en.wikipedia.org/wiki/Test-driven_development) for more detail.

**Pull request merged**
